# Generated by Django 5.2.4 on 2025-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.CharField(max_length=500, verbose_name='Quote Text')),
                ('quote_author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quote Author')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['quote_author'],
            },
        ),
    ]
