# Generated by Django 5.2.4 on 2025-07-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quote Category'),
        ),
    ]
