# Generated by Django 5.2.4 on 2025-07-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_quote_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Quote Dislikes'),
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Quote Likes'),
        ),
        migrations.AddField(
            model_name='quote',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Quote Weight'),
        ),
    ]
