# Generated by Django 5.2.4 on 2025-07-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_quote_dislikes_quote_likes_quote_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='weight',
        ),
    ]
