# Generated by Django 5.2.4 on 2025-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0004_remove_quote_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Quote Views'),
        ),
    ]
